[package]
name = "rsoderh-simd"
version = "0.1.0"
edition = "2024"

[dependencies]
approx = "0.5.1"
bytemuck = "1.24.0"

[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }


[[bench]]
name = "matrix"
harness = false
